name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Sæt Python op
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer detect-secrets
        run: pip install detect-secrets

      - name: Scan for secrets
        run: |
          detect-secrets scan --json > current_scan.json
          echo "Scan completed successfully"

  build:
    runs-on: ubuntu-latest
    needs: detect-secrets

    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Sæt Python op
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer pakker
        run: pip install -r requirements.txt

      - name: Byg Docker image
        run: docker build -t iot-predictive-maintenance .